services:
  - type: web
    name: automation-mail-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: OPENAI_API_KEY
        sync: false
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_DATABASE_ID
        sync: false
      - key: SANITY_PROJECT_ID
        sync: false
      - key: SANITY_DATASET
        value: production
      - key: SANITY_TOKEN
        sync: false
